name: CI semver.xq
on: [push, pull_request]
jobs:
  build:
    name: Build and Test Semver.xq (${{ matrix.os }} / JDK ${{ matrix.jdk }} / eXist-db ${{ matrix.exist-version }})
    strategy:
      fail-fast: true
      matrix:
        jdk: ['8', '11']
        exist-version: ['4.2.0', '5.1.0', '6.1.0-SNAPSHOT']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.exist-version }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.exist-version }}-maven
      - name: Maven Build
        run: |
          if [[ "${{ matrix.exist-version }}" == "4.2.0" ]]; then
              mvn -V clean package -DskipTests
          else
              mvn -V clean package -DskipTests -Pexistdb-5-or-newer -Dexist.version=${{ matrix.exist-version }}
          fi
      - name: Test
        run: |
          if [[ "${{ matrix.exist-version }}" == "4.2.0" ]]; then
              mvn verify
          else
              mvn verify -Pexistdb-5-or-newer -Dexist.version=${{ matrix.exist-version }}
          fi
